const { app, BrowserWindow, ipcMain, dialog } = require('electron');
const path = require('path');
const fs   = require('fs');

// ── Window ───────────────────────────────────────────────────────────────────
function createWindow() {
  const win = new BrowserWindow({
    width: 720,
    height: 720,
    minWidth: 560,
    title: 'EyzTools – Minecraft Pack Generator',
    autoHideMenuBar: true,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,   // security: renderer can't access Node directly
      nodeIntegration: false,
    },
  });

  win.loadFile(path.join(__dirname, 'renderer', 'index.html'));
}

// ── IPC: choose output folder ─────────────────────────────────────────────────
ipcMain.handle('choose-output-folder', async () => {
  const { canceled, filePaths } = await dialog.showOpenDialog({
    title: 'Choose output folder for the resource pack',
    properties: ['openDirectory', 'createDirectory'],
  });
  return canceled ? null : filePaths[0];
});

// ── IPC: generate resource pack ───────────────────────────────────────────────
ipcMain.handle('generate-pack', async (_event, payload) => {
  const { customModelData, modelName, selectedItem, modelJson, outputPath } = payload;

  try {
    // Validate JSON content before touching the disk
    JSON.parse(modelJson);
  } catch {
    return { success: false, message: 'The model file is not valid JSON.' };
  }

  try {
    const modelsItemDir   = path.join(outputPath, 'assets', 'minecraft', 'models', 'item');
    const texturesItemDir = path.join(outputPath, 'assets', 'minecraft', 'textures', 'item');

    // Create directories (no-op if they already exist)
    fs.mkdirSync(modelsItemDir,   { recursive: true });
    fs.mkdirSync(texturesItemDir, { recursive: true });

    // pack.mcmeta ──────────────────────────────────────────────────────────
    const mcmeta = {
      pack: { pack_format: 15, description: 'Generated by EyzTools' },
    };
    fs.writeFileSync(
      path.join(outputPath, 'pack.mcmeta'),
      JSON.stringify(mcmeta, null, 2),
    );

    // Uploaded Blockbench model ────────────────────────────────────────────
    fs.writeFileSync(
      path.join(modelsItemDir, `${modelName}.json`),
      modelJson,
    );

    // Override JSON for the chosen vanilla item ────────────────────────────
    const overrideJson = {
      parent: 'item/generated',
      textures: { layer0: `item/${selectedItem}` },
      overrides: [
        {
          predicate: { custom_model_data: customModelData },
          model: `item/${modelName}`,
        },
      ],
    };
    fs.writeFileSync(
      path.join(modelsItemDir, `${selectedItem}.json`),
      JSON.stringify(overrideJson, null, 2),
    );

    return {
      success: true,
      message: `Resource pack generated successfully!\n\nLocation:\n${outputPath}`,
    };
  } catch (err) {
    return { success: false, message: `File system error: ${err.message}` };
  }
});

// ── App lifecycle ─────────────────────────────────────────────────────────────
app.whenReady().then(() => {
  createWindow();

  // macOS: re-create window when dock icon is clicked
  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});
