use std::fs;
use std::path::Path;

/// Payload sent from the frontend to generate the resource pack.
#[derive(serde::Deserialize)]
pub struct GeneratePayload {
    pub custom_model_data: u32,
    pub model_name: String,
    pub selected_item: String,
    pub model_json: String,
    pub output_path: String,
}

#[derive(serde::Serialize)]
pub struct GenerateResult {
    pub success: bool,
    pub message: String,
}

#[tauri::command]
pub fn generate_resource_pack(payload: GeneratePayload) -> GenerateResult {
    match write_pack(&payload) {
        Ok(msg) => GenerateResult { success: true, message: msg },
        Err(e)  => GenerateResult { success: false, message: format!("Error: {e}") },
    }
}

fn write_pack(p: &GeneratePayload) -> Result<String, String> {
    let base = Path::new(&p.output_path);

    let models_item  = base.join("assets/minecraft/models/item");
    let textures_item = base.join("assets/minecraft/textures/item");

    fs::create_dir_all(&models_item)
        .map_err(|e| format!("Cannot create models/item dir: {e}"))?;
    fs::create_dir_all(&textures_item)
        .map_err(|e| format!("Cannot create textures/item dir: {e}"))?;

    // pack.mcmeta
    let mcmeta = serde_json::json!({
        "pack": { "pack_format": 15, "description": "Generated by EyzTools" }
    });
    write_json(base.join("pack.mcmeta"), &mcmeta)?;

    // Validate and write the uploaded model file
    let _: serde_json::Value = serde_json::from_str(&p.model_json)
        .map_err(|e| format!("Model file is not valid JSON: {e}"))?;
    fs::write(models_item.join(format!("{}.json", p.model_name)), &p.model_json)
        .map_err(|e| format!("Cannot write model file: {e}"))?;

    // Override JSON for the selected item
    let override_json = serde_json::json!({
        "parent": "item/generated",
        "textures": { "layer0": format!("item/{}", p.selected_item) },
        "overrides": [{
            "predicate": { "custom_model_data": p.custom_model_data },
            "model": format!("item/{}", p.model_name)
        }]
    });
    write_json(models_item.join(format!("{}.json", p.selected_item)), &override_json)?;

    Ok(format!("Resource pack generated at:\n{}", base.display()))
}

fn write_json(path: impl AsRef<Path>, value: &serde_json::Value) -> Result<(), String> {
    let content = serde_json::to_string_pretty(value)
        .map_err(|e| format!("JSON serialization error: {e}"))?;
    fs::write(&path, content)
        .map_err(|e| format!("Cannot write {}: {e}", path.as_ref().display()))
}
